/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BikeListing {
  'id' : string,
  'model' : string,
  'title' : string,
  'contactInfo' : string,
  'mileage' : [] | [bigint],
  'year' : bigint,
  'description' : string,
  'seller' : Principal,
  'listingDate' : bigint,
  'available' : boolean,
  'brand' : string,
  'price' : bigint,
  'condition' : Condition,
}
export type Condition = { 'fair' : null } |
  { 'good' : null } |
  { 'excellent' : null };
export interface FounderProfile {
  'instagramProfile' : string,
  'name' : string,
  'address' : string,
  'contactNumber' : string,
  'emailAddress' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'listingId' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface UserProfile { 'contactInfo' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      [] | [bigint],
      Condition,
      string,
      string,
    ],
    string
  >,
  'deleteListing' : ActorMethod<[string], undefined>,
  'getAllListings' : ActorMethod<[], Array<BikeListing>>,
  'getAvailableListings' : ActorMethod<[], Array<BikeListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFounderProfile' : ActorMethod<[], [] | [FounderProfile]>,
  'getListing' : ActorMethod<[string], BikeListing>,
  'getMessagesForListing' : ActorMethod<[string], Array<Message>>,
  'getMyListings' : ActorMethod<[], Array<BikeListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeFounder' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFounder' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListingsByBrand' : ActorMethod<[string], Array<BikeListing>>,
  'searchListingsByPriceRange' : ActorMethod<
    [bigint, bigint],
    Array<BikeListing>
  >,
  'sendMessage' : ActorMethod<[Principal, string, string], undefined>,
  'updateFounderProfile' : ActorMethod<[FounderProfile], undefined>,
  'updateListing' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      [] | [bigint],
      Condition,
      string,
      string,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];