/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UsageStat = IDL.Record({
  'visitors' : IDL.Nat,
  'listings' : IDL.Nat,
  'timestamp' : IDL.Int,
  'users' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Condition = IDL.Variant({
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'excellent' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BuyerProfile = IDL.Record({
  'aadhaarDocument' : IDL.Opt(ExternalBlob),
  'createdAt' : IDL.Int,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'panDocument' : IDL.Opt(ExternalBlob),
  'fullName' : IDL.Text,
  'isProfileComplete' : IDL.Bool,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'panNumber' : IDL.Text,
  'aadhaarNumber' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const BikeListing = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'mileage' : IDL.Opt(IDL.Nat),
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'listingDate' : IDL.Int,
  'available' : IDL.Bool,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : Condition,
});
export const AnalyticsData = IDL.Record({
  'activeListings' : IDL.Nat,
  'totalVisitors' : IDL.Nat,
  'usageStats' : IDL.Vec(UsageStat),
  'registeredUsers' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
});
export const FounderProfile = IDL.Record({
  'instagramProfile' : IDL.Text,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactNumber' : IDL.Text,
  'emailAddress' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'listingId' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const WebsiteContent = IDL.Record({
  'heroSection' : IDL.Text,
  'aboutPage' : IDL.Text,
  'footerInfo' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addUsageStat' : IDL.Func([UsageStat], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeBuyerProfile' : IDL.Func([], [], []),
  'createBuyerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Condition,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'getAllBuyerProfiles' : IDL.Func([], [IDL.Vec(BuyerProfile)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
  'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
  'getAvailableListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
  'getBuyerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BuyerProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFounderProfile' : IDL.Func([], [IDL.Opt(FounderProfile)], ['query']),
  'getListing' : IDL.Func([IDL.Text], [BikeListing], ['query']),
  'getMessagesForListing' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getMyBuyerProfile' : IDL.Func([], [IDL.Opt(BuyerProfile)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'initializeFounder' : IDL.Func([], [], []),
  'isBuyerProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFounder' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListingsByBrand' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BikeListing)],
      ['query'],
    ),
  'searchListingsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BikeListing)],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
  'updateFounderProfile' : IDL.Func([FounderProfile], [], []),
  'updateListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        Condition,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
  'uploadAadhaarDocument' : IDL.Func([ExternalBlob], [], []),
  'uploadPanDocument' : IDL.Func([ExternalBlob], [], []),
  'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UsageStat = IDL.Record({
    'visitors' : IDL.Nat,
    'listings' : IDL.Nat,
    'timestamp' : IDL.Int,
    'users' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Condition = IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'excellent' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BuyerProfile = IDL.Record({
    'aadhaarDocument' : IDL.Opt(ExternalBlob),
    'createdAt' : IDL.Int,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'panDocument' : IDL.Opt(ExternalBlob),
    'fullName' : IDL.Text,
    'isProfileComplete' : IDL.Bool,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'panNumber' : IDL.Text,
    'aadhaarNumber' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const BikeListing = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'mileage' : IDL.Opt(IDL.Nat),
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'listingDate' : IDL.Int,
    'available' : IDL.Bool,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : Condition,
  });
  const AnalyticsData = IDL.Record({
    'activeListings' : IDL.Nat,
    'totalVisitors' : IDL.Nat,
    'usageStats' : IDL.Vec(UsageStat),
    'registeredUsers' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
  });
  const FounderProfile = IDL.Record({
    'instagramProfile' : IDL.Text,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactNumber' : IDL.Text,
    'emailAddress' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'listingId' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const WebsiteContent = IDL.Record({
    'heroSection' : IDL.Text,
    'aboutPage' : IDL.Text,
    'footerInfo' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addUsageStat' : IDL.Func([UsageStat], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeBuyerProfile' : IDL.Func([], [], []),
    'createBuyerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Condition,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'getAllBuyerProfiles' : IDL.Func([], [IDL.Vec(BuyerProfile)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
    'getAnalyticsData' : IDL.Func([], [AnalyticsData], ['query']),
    'getAvailableListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
    'getBuyerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BuyerProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFounderProfile' : IDL.Func([], [IDL.Opt(FounderProfile)], ['query']),
    'getListing' : IDL.Func([IDL.Text], [BikeListing], ['query']),
    'getMessagesForListing' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyBuyerProfile' : IDL.Func([], [IDL.Opt(BuyerProfile)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(BikeListing)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'initializeFounder' : IDL.Func([], [], []),
    'isBuyerProfileComplete' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFounder' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListingsByBrand' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BikeListing)],
        ['query'],
      ),
    'searchListingsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BikeListing)],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [], []),
    'updateFounderProfile' : IDL.Func([FounderProfile], [], []),
    'updateListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          Condition,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
    'uploadAadhaarDocument' : IDL.Func([ExternalBlob], [], []),
    'uploadPanDocument' : IDL.Func([ExternalBlob], [], []),
    'uploadProfilePhoto' : IDL.Func([ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };