/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface FounderProfile {
    instagramProfile: string;
    name: string;
    address: string;
    contactNumber: string;
    emailAddress: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BuyerProfile {
    aadhaarDocument?: ExternalBlob;
    createdAt: bigint;
    profilePhoto?: ExternalBlob;
    panDocument?: ExternalBlob;
    fullName: string;
    isProfileComplete: boolean;
    email: string;
    address: string;
    panNumber: string;
    aadhaarNumber: string;
    phoneNumber: string;
}
export interface UsageStat {
    visitors: bigint;
    listings: bigint;
    timestamp: bigint;
    users: bigint;
}
export interface Message {
    id: string;
    content: string;
    listingId: string;
    sender: Principal;
    timestamp: bigint;
    receiver: Principal;
}
export interface BikeListing {
    id: string;
    model: string;
    title: string;
    contactInfo: string;
    mileage?: bigint;
    year: bigint;
    description: string;
    seller: Principal;
    listingDate: bigint;
    available: boolean;
    brand: string;
    price: bigint;
    condition: Condition;
}
export interface WebsiteContent {
    heroSection: string;
    aboutPage: string;
    footerInfo: string;
}
export interface UserProfile {
    contactInfo: string;
    name: string;
}
export interface AnalyticsData {
    activeListings: bigint;
    totalVisitors: bigint;
    usageStats: Array<UsageStat>;
    registeredUsers: bigint;
}
export enum Condition {
    fair = "fair",
    good = "good",
    excellent = "excellent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addUsageStat(stat: UsageStat): Promise<void>;
    adminLogin(email: string, password: string): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeBuyerProfile(): Promise<void>;
    createBuyerProfile(fullName: string, phoneNumber: string, email: string, address: string, aadhaarNumber: string, panNumber: string): Promise<void>;
    createListing(title: string, brand: string, model: string, year: bigint, price: bigint, mileage: bigint | null, condition: Condition, description: string, contactInfo: string): Promise<string>;
    deleteListing(id: string): Promise<void>;
    getAllBuyerProfiles(): Promise<Array<BuyerProfile>>;
    getAllListings(): Promise<Array<BikeListing>>;
    getAnalyticsData(): Promise<AnalyticsData>;
    getAvailableListings(): Promise<Array<BikeListing>>;
    getBuyerProfile(user: Principal): Promise<BuyerProfile | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFounderProfile(): Promise<FounderProfile | null>;
    getListing(id: string): Promise<BikeListing>;
    getMessagesForListing(listingId: string): Promise<Array<Message>>;
    getMyBuyerProfile(): Promise<BuyerProfile | null>;
    getMyListings(): Promise<Array<BikeListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWebsiteContent(): Promise<WebsiteContent>;
    initializeFounder(): Promise<void>;
    isBuyerProfileComplete(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isFounder(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchListingsByBrand(brand: string): Promise<Array<BikeListing>>;
    searchListingsByPriceRange(minPrice: bigint, maxPrice: bigint): Promise<Array<BikeListing>>;
    sendMessage(receiver: Principal, content: string, listingId: string): Promise<void>;
    updateFounderProfile(profile: FounderProfile): Promise<void>;
    updateListing(id: string, title: string, brand: string, model: string, year: bigint, price: bigint, mileage: bigint | null, condition: Condition, description: string, contactInfo: string, available: boolean): Promise<void>;
    updateWebsiteContent(content: WebsiteContent): Promise<void>;
    uploadAadhaarDocument(blob: ExternalBlob): Promise<void>;
    uploadPanDocument(blob: ExternalBlob): Promise<void>;
    uploadProfilePhoto(blob: ExternalBlob): Promise<void>;
}
import type { BikeListing as _BikeListing, BuyerProfile as _BuyerProfile, Condition as _Condition, ExternalBlob as _ExternalBlob, FounderProfile as _FounderProfile, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addUsageStat(arg0: UsageStat): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUsageStat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUsageStat(arg0);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeBuyerProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBuyerProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBuyerProfile();
            return result;
        }
    }
    async createBuyerProfile(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBuyerProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBuyerProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createListing(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint | null, arg6: Condition, arg7: string, arg8: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_Condition_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_Condition_n11(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
    async deleteListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteListing(arg0);
            return result;
        }
    }
    async getAllBuyerProfiles(): Promise<Array<BuyerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBuyerProfiles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBuyerProfiles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<BikeListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsData(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsData();
            return result;
        }
    }
    async getAvailableListings(): Promise<Array<BikeListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBuyerProfile(arg0: Principal): Promise<BuyerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuyerProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuyerProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFounderProfile(): Promise<FounderProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFounderProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFounderProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListing(arg0: string): Promise<BikeListing> {
        if (this.processError) {
            try {
                const result = await this.actor.getListing(arg0);
                return from_candid_BikeListing_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListing(arg0);
            return from_candid_BikeListing_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesForListing(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesForListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesForListing(arg0);
            return result;
        }
    }
    async getMyBuyerProfile(): Promise<BuyerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBuyerProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBuyerProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<BikeListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWebsiteContent(): Promise<WebsiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteContent();
            return result;
        }
    }
    async initializeFounder(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeFounder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeFounder();
            return result;
        }
    }
    async isBuyerProfileComplete(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBuyerProfileComplete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBuyerProfileComplete();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isFounder(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFounder();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFounder();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchListingsByBrand(arg0: string): Promise<Array<BikeListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByBrand(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByBrand(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchListingsByPriceRange(arg0: bigint, arg1: bigint): Promise<Array<BikeListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchListingsByPriceRange(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchListingsByPriceRange(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async updateFounderProfile(arg0: FounderProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFounderProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFounderProfile(arg0);
            return result;
        }
    }
    async updateListing(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint | null, arg7: Condition, arg8: string, arg9: string, arg10: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), to_candid_Condition_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListing(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6), to_candid_Condition_n11(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10);
            return result;
        }
    }
    async updateWebsiteContent(arg0: WebsiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebsiteContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebsiteContent(arg0);
            return result;
        }
    }
    async uploadAadhaarDocument(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadAadhaarDocument(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadAadhaarDocument(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadPanDocument(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPanDocument(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPanDocument(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadProfilePhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePhoto(await to_candid_ExternalBlob_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_BikeListing_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BikeListing): BikeListing {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_BuyerProfile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuyerProfile): Promise<BuyerProfile> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Condition_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Condition): Condition {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BuyerProfile]): Promise<BuyerProfile | null> {
    return value.length === 0 ? null : await from_candid_BuyerProfile_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FounderProfile]): FounderProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aadhaarDocument: [] | [_ExternalBlob];
    createdAt: bigint;
    profilePhoto: [] | [_ExternalBlob];
    panDocument: [] | [_ExternalBlob];
    fullName: string;
    isProfileComplete: boolean;
    email: string;
    address: string;
    panNumber: string;
    aadhaarNumber: string;
    phoneNumber: string;
}): Promise<{
    aadhaarDocument?: ExternalBlob;
    createdAt: bigint;
    profilePhoto?: ExternalBlob;
    panDocument?: ExternalBlob;
    fullName: string;
    isProfileComplete: boolean;
    email: string;
    address: string;
    panNumber: string;
    aadhaarNumber: string;
    phoneNumber: string;
}> {
    return {
        aadhaarDocument: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.aadhaarDocument)),
        createdAt: value.createdAt,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.profilePhoto)),
        panDocument: record_opt_to_undefined(await from_candid_opt_n16(_uploadFile, _downloadFile, value.panDocument)),
        fullName: value.fullName,
        isProfileComplete: value.isProfileComplete,
        email: value.email,
        address: value.address,
        panNumber: value.panNumber,
        aadhaarNumber: value.aadhaarNumber,
        phoneNumber: value.phoneNumber
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    model: string;
    title: string;
    contactInfo: string;
    mileage: [] | [bigint];
    year: bigint;
    description: string;
    seller: Principal;
    listingDate: bigint;
    available: boolean;
    brand: string;
    price: bigint;
    condition: _Condition;
}): {
    id: string;
    model: string;
    title: string;
    contactInfo: string;
    mileage?: bigint;
    year: bigint;
    description: string;
    seller: Principal;
    listingDate: bigint;
    available: boolean;
    brand: string;
    price: bigint;
    condition: Condition;
} {
    return {
        id: value.id,
        model: value.model,
        title: value.title,
        contactInfo: value.contactInfo,
        mileage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.mileage)),
        year: value.year,
        description: value.description,
        seller: value.seller,
        listingDate: value.listingDate,
        available: value.available,
        brand: value.brand,
        price: value.price,
        condition: from_candid_Condition_n21(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fair: null;
} | {
    good: null;
} | {
    excellent: null;
}): Condition {
    return "fair" in value ? Condition.fair : "good" in value ? Condition.good : "excellent" in value ? Condition.excellent : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BuyerProfile>): Promise<Array<BuyerProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BuyerProfile_n14(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BikeListing>): Array<BikeListing> {
    return value.map((x)=>from_candid_BikeListing_n19(_uploadFile, _downloadFile, x));
}
function to_candid_Condition_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): _Condition {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Condition): {
    fair: null;
} | {
    good: null;
} | {
    excellent: null;
} {
    return value == Condition.fair ? {
        fair: null
    } : value == Condition.good ? {
        good: null
    } : value == Condition.excellent ? {
        excellent: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
